version: 0.0
os: windows
files:
  - source: RockWeb
    destination: C:\inetpub\wwwroot\
hooks:
  ApplicationStop:
    - location: deploy\iisStop.bat
      timeout: 20
  ApplicationStart:
    - location: deploy\iisStart.bat
      timeout: 20
